name: echo
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.12
  - sphinx
  - pytest
  - setuptools
  - optuna
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - jupyter_server
  - distributed
  - pip
  - pyarrow
  - xgboost
  - pip:
    - .
